# Generated by Django 3.1.5 on 2021-02-06 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210206_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a37eea6c-1bbd-4681-a418-b6c39c07b25c'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
